title: "Eve Wang — Physics x CS"
subtitle: "Quantum, Materials, Scientific Computing, Outreach"

# REQUIRED for your repo
repository: "eve/personal_test"
url: "https://eve.github.io"
baseurl: "/personal_test"

remote_theme: "academicpages/academicpages"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

author:
  name: "Hung-Yu (Eve) Wang"
  avatar: "assets/img/hero.jpg"
  bio: "Physics x CS | NTU Physics Talent Program · NSRRC AES/AED · TEDx"
  location: "Hsinchu, Taiwan"
  email: "eve.applications@proton.me"
  github: "eve"

collections:
  teaching:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true

teaser: "assets/img/hero.jpg"
last_updated: "2025-10"
